// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxwErtLbXeoPhZtfoUP_I6KAnsIdTCg0I',
    appId: '1:1077479720410:web:b2d839d23e44c8350a6ce3',
    messagingSenderId: '1077479720410',
    projectId: 'thepillr2',
    authDomain: 'thepillr2.firebaseapp.com',
    storageBucket: 'thepillr2.firebasestorage.app',
    measurementId: 'G-EERMHH8JNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBV8YapZWAx2uzJrQacW1_fu4NqJAqRE',
    appId: '1:1077479720410:android:bee47285633ea5150a6ce3',
    messagingSenderId: '1077479720410',
    projectId: 'thepillr2',
    storageBucket: 'thepillr2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY-Ds8wvY5EBS-diKJHefRPwR2mvrIypo',
    appId: '1:1077479720410:ios:567de8d381557d0f0a6ce3',
    messagingSenderId: '1077479720410',
    projectId: 'thepillr2',
    storageBucket: 'thepillr2.firebasestorage.app',
    iosBundleId: 'com.pillr.thePillr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY-Ds8wvY5EBS-diKJHefRPwR2mvrIypo',
    appId: '1:1077479720410:ios:9ac0675cf22c65210a6ce3',
    messagingSenderId: '1077479720410',
    projectId: 'thepillr2',
    storageBucket: 'thepillr2.firebasestorage.app',
    iosBundleId: 'com.thepillr.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxwErtLbXeoPhZtfoUP_I6KAnsIdTCg0I',
    appId: '1:1077479720410:web:c4dc2ad488adc8aa0a6ce3',
    messagingSenderId: '1077479720410',
    projectId: 'thepillr2',
    authDomain: 'thepillr2.firebaseapp.com',
    storageBucket: 'thepillr2.firebasestorage.app',
    measurementId: 'G-GSL6VV6468',
  );

}